// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "location.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace amber {
namespace location_proto {

namespace {


}  // namespace


void protobuf_AssignDesc_location_2eproto() {
  protobuf_AddDesc_location_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "location.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_location_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_location_2eproto() {
}

void protobuf_AddDesc_location_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::amber::protobuf_AddDesc_drivermsg_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016location.proto\022\024amber.location_proto\032\017"
    "drivermsg.proto:&\n\014get_location\022\020.amber."
    "DriverMsg\030\036 \001(\010:\033\n\001x\022\020.amber.DriverMsg\030\037"
    " \001(\001:\033\n\001y\022\020.amber.DriverMsg\030  \001(\001B0\n\037pl."
    "edu.agh.amber.location.protoB\rLocationPr"
    "oto", 203);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "location.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::amber::DriverMsg::default_instance(),
    30, 8, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::amber::DriverMsg::default_instance(),
    31, 1, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::amber::DriverMsg::default_instance(),
    32, 1, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_location_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_location_2eproto {
  StaticDescriptorInitializer_location_2eproto() {
    protobuf_AddDesc_location_2eproto();
  }
} static_descriptor_initializer_location_2eproto_;

::google::protobuf::internal::ExtensionIdentifier< ::amber::DriverMsg,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  get_location(kGetLocationFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::amber::DriverMsg,
    ::google::protobuf::internal::PrimitiveTypeTraits< double >, 1, false >
  x(kXFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::amber::DriverMsg,
    ::google::protobuf::internal::PrimitiveTypeTraits< double >, 1, false >
  y(kYFieldNumber, 0);

// @@protoc_insertion_point(namespace_scope)

}  // namespace location_proto
}  // namespace amber

// @@protoc_insertion_point(global_scope)
